import os
import tempfile

import pandas as pd

from common import download_file, generate_symbol
from database.base import DuckDBBase


# 基于 DuckDBBase 的 SW类
class ShenWan(DuckDBBase):
    def __init__(self):
        super().__init__()
        self.table_name = "raw_shenwan_industry"
        self._create_shenwan_table()

    def _create_shenwan_table(self):
        """创建表"""
        columns = {
            "symbol": "varchar",
            "class_code": "varchar",
            "l1_class": "varchar",
            "l2_class": "varchar",
            "l3_class": "varchar",
        }
        self.create_table(self.table_name, columns)

    def query(self) -> pd.DataFrame:
        return self.select(table_name=self.table_name)

    def store_stock_class(self, xls_file: str):
        # Excel 列名到数据库列名的映射
        xls_column_mapping = {
            "股票代码": "code",
            "计入日期": "date",
            "行业代码": "class_code",
            "更新日期": "update_date",
        }

        try:
            # 读取 Excel 文件
            df = pd.read_excel(xls_file, dtype=str)
            # 重命名列
            df.rename(columns=xls_column_mapping, inplace=True)

            sw_df = pd.DataFrame(shenwan_class_code)

            df = df.loc[df.groupby(["code"])["date"].idxmax()]
            df["symbol"] = df["code"].apply(generate_symbol)
            df.drop(columns=["code"], inplace=True)
            data = pd.merge(
                df[["symbol", "class_code"]],
                sw_df[["class_code", "l1_class", "l2_class", "l3_class"]],
                left_on="class_code",
                right_on="class_code",
                how="left",
            )
            data.dropna(inplace=True)
            self.truncate_table(self.table_name)
            self.insert_dataframe(self.table_name, data)

        except Exception as e:
            raise e


shenwan = ShenWan()


def run_shenwan_industry_update():
    print(f"\n{'=' * 50}\n开始更新申万行业信息")
    with tempfile.TemporaryDirectory() as temp_dir:
        os.makedirs(temp_dir, exist_ok=True)
        url = "https://www.swsresearch.com/swindex/pdf/SwClass2021/StockClassifyUse_stock.xls"
        file_name = "sw_stock_class.xls"
        headers = {
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
            "Content-Type": "application/json",
        }

        output_path = os.path.join(temp_dir, file_name)
        if download_file(url, output_path, headers=headers):
            try:
                shenwan.store_stock_class(xls_file=output_path)
            except Exception as e:
                raise e
        else:
            print(f"❌ 文件下载失败：{file_name}")

    print(f"🎉 申万行业信息更新完成\n{'=' * 50}\n")


shenwan_class_code = [
    {
        "class_code": "110000",
        "l1_class": "农林牧渔",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "110100",
        "l1_class": "农林牧渔",
        "l2_class": "种植业",
        "l3_class": "",
    },
    {
        "class_code": "110101",
        "l1_class": "农林牧渔",
        "l2_class": "种植业",
        "l3_class": "种子",
    },
    {
        "class_code": "110102",
        "l1_class": "农林牧渔",
        "l2_class": "种植业",
        "l3_class": "粮食种植",
    },
    {
        "class_code": "110103",
        "l1_class": "农林牧渔",
        "l2_class": "种植业",
        "l3_class": "其他种植业",
    },
    {
        "class_code": "110104",
        "l1_class": "农林牧渔",
        "l2_class": "种植业",
        "l3_class": "食用菌",
    },
    {
        "class_code": "110200",
        "l1_class": "农林牧渔",
        "l2_class": "渔业",
        "l3_class": "",
    },
    {
        "class_code": "110201",
        "l1_class": "农林牧渔",
        "l2_class": "渔业",
        "l3_class": "海洋捕捞",
    },
    {
        "class_code": "110202",
        "l1_class": "农林牧渔",
        "l2_class": "渔业",
        "l3_class": "水产养殖",
    },
    {
        "class_code": "110300",
        "l1_class": "农林牧渔",
        "l2_class": "林业Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "110301",
        "l1_class": "农林牧渔",
        "l2_class": "林业Ⅱ",
        "l3_class": "林业Ⅲ",
    },
    {
        "class_code": "110400",
        "l1_class": "农林牧渔",
        "l2_class": "饲料",
        "l3_class": "",
    },
    {
        "class_code": "110402",
        "l1_class": "农林牧渔",
        "l2_class": "饲料",
        "l3_class": "畜禽饲料",
    },
    {
        "class_code": "110403",
        "l1_class": "农林牧渔",
        "l2_class": "饲料",
        "l3_class": "水产饲料",
    },
    {
        "class_code": "110404",
        "l1_class": "农林牧渔",
        "l2_class": "饲料",
        "l3_class": "宠物食品",
    },
    {
        "class_code": "110500",
        "l1_class": "农林牧渔",
        "l2_class": "农产品加工",
        "l3_class": "",
    },
    {
        "class_code": "110501",
        "l1_class": "农林牧渔",
        "l2_class": "农产品加工",
        "l3_class": "果蔬加工",
    },
    {
        "class_code": "110502",
        "l1_class": "农林牧渔",
        "l2_class": "农产品加工",
        "l3_class": "粮油加工",
    },
    {
        "class_code": "110504",
        "l1_class": "农林牧渔",
        "l2_class": "农产品加工",
        "l3_class": "其他农产品加工",
    },
    {
        "class_code": "110700",
        "l1_class": "农林牧渔",
        "l2_class": "养殖业",
        "l3_class": "",
    },
    {
        "class_code": "110702",
        "l1_class": "农林牧渔",
        "l2_class": "养殖业",
        "l3_class": "生猪养殖",
    },
    {
        "class_code": "110703",
        "l1_class": "农林牧渔",
        "l2_class": "养殖业",
        "l3_class": "肉鸡养殖",
    },
    {
        "class_code": "110704",
        "l1_class": "农林牧渔",
        "l2_class": "养殖业",
        "l3_class": "其他养殖",
    },
    {
        "class_code": "110800",
        "l1_class": "农林牧渔",
        "l2_class": "动物保健Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "110801",
        "l1_class": "农林牧渔",
        "l2_class": "动物保健Ⅱ",
        "l3_class": "动物保健Ⅲ",
    },
    {
        "class_code": "110900",
        "l1_class": "农林牧渔",
        "l2_class": "农业综合Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "110901",
        "l1_class": "农林牧渔",
        "l2_class": "农业综合Ⅱ",
        "l3_class": "农业综合Ⅲ",
    },
    {
        "class_code": "220000",
        "l1_class": "基础化工",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "220200",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "",
    },
    {
        "class_code": "220201",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "纯碱",
    },
    {
        "class_code": "220202",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "氯碱",
    },
    {
        "class_code": "220203",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "无机盐",
    },
    {
        "class_code": "220204",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "其他化学原料",
    },
    {
        "class_code": "220205",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "煤化工",
    },
    {
        "class_code": "220206",
        "l1_class": "基础化工",
        "l2_class": "化学原料",
        "l3_class": "钛白粉",
    },
    {
        "class_code": "220300",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "",
    },
    {
        "class_code": "220305",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "涂料油墨",
    },
    {
        "class_code": "220307",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "民爆制品",
    },
    {
        "class_code": "220308",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "纺织化学制品",
    },
    {
        "class_code": "220309",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "其他化学制品",
    },
    {
        "class_code": "220311",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "氟化工",
    },
    {
        "class_code": "220313",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "聚氨酯",
    },
    {
        "class_code": "220315",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "食品及饲料添加剂",
    },
    {
        "class_code": "220316",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "有机硅",
    },
    {
        "class_code": "220317",
        "l1_class": "基础化工",
        "l2_class": "化学制品",
        "l3_class": "胶黏剂及胶带",
    },
    {
        "class_code": "220400",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "",
    },
    {
        "class_code": "220401",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "涤纶",
    },
    {
        "class_code": "220403",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "粘胶",
    },
    {
        "class_code": "220404",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "其他化学纤维",
    },
    {
        "class_code": "220405",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "氨纶",
    },
    {
        "class_code": "220406",
        "l1_class": "基础化工",
        "l2_class": "化学纤维",
        "l3_class": "锦纶",
    },
    {
        "class_code": "220500",
        "l1_class": "基础化工",
        "l2_class": "塑料",
        "l3_class": "",
    },
    {
        "class_code": "220501",
        "l1_class": "基础化工",
        "l2_class": "塑料",
        "l3_class": "其他塑料制品",
    },
    {
        "class_code": "220503",
        "l1_class": "基础化工",
        "l2_class": "塑料",
        "l3_class": "改性塑料",
    },
    {
        "class_code": "220504",
        "l1_class": "基础化工",
        "l2_class": "塑料",
        "l3_class": "合成树脂",
    },
    {
        "class_code": "220505",
        "l1_class": "基础化工",
        "l2_class": "塑料",
        "l3_class": "膜材料",
    },
    {
        "class_code": "220600",
        "l1_class": "基础化工",
        "l2_class": "橡胶",
        "l3_class": "",
    },
    {
        "class_code": "220602",
        "l1_class": "基础化工",
        "l2_class": "橡胶",
        "l3_class": "其他橡胶制品",
    },
    {
        "class_code": "220603",
        "l1_class": "基础化工",
        "l2_class": "橡胶",
        "l3_class": "炭黑",
    },
    {
        "class_code": "220604",
        "l1_class": "基础化工",
        "l2_class": "橡胶",
        "l3_class": "橡胶助剂",
    },
    {
        "class_code": "220800",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "",
    },
    {
        "class_code": "220801",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "氮肥",
    },
    {
        "class_code": "220802",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "磷肥及磷化工",
    },
    {
        "class_code": "220803",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "农药",
    },
    {
        "class_code": "220804",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "钾肥",
    },
    {
        "class_code": "220805",
        "l1_class": "基础化工",
        "l2_class": "农化制品",
        "l3_class": "复合肥",
    },
    {
        "class_code": "220900",
        "l1_class": "基础化工",
        "l2_class": "非金属材料Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "220901",
        "l1_class": "基础化工",
        "l2_class": "非金属材料Ⅱ",
        "l3_class": "非金属材料Ⅲ",
    },
    {"class_code": "230000", "l1_class": "钢铁", "l2_class": "", "l3_class": ""},
    {
        "class_code": "230300",
        "l1_class": "钢铁",
        "l2_class": "冶钢原料",
        "l3_class": "",
    },
    {
        "class_code": "230301",
        "l1_class": "钢铁",
        "l2_class": "冶钢原料",
        "l3_class": "铁矿石",
    },
    {
        "class_code": "230302",
        "l1_class": "钢铁",
        "l2_class": "冶钢原料",
        "l3_class": "冶钢辅料",
    },
    {
        "class_code": "230400",
        "l1_class": "钢铁",
        "l2_class": "普钢",
        "l3_class": "",
    },
    {
        "class_code": "230401",
        "l1_class": "钢铁",
        "l2_class": "普钢",
        "l3_class": "长材",
    },
    {
        "class_code": "230402",
        "l1_class": "钢铁",
        "l2_class": "普钢",
        "l3_class": "板材",
    },
    {
        "class_code": "230403",
        "l1_class": "钢铁",
        "l2_class": "普钢",
        "l3_class": "钢铁管材",
    },
    {
        "class_code": "230500",
        "l1_class": "钢铁",
        "l2_class": "特钢Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "230501",
        "l1_class": "钢铁",
        "l2_class": "特钢Ⅱ",
        "l3_class": "特钢Ⅲ",
    },
    {
        "class_code": "240000",
        "l1_class": "有色金属",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "240200",
        "l1_class": "有色金属",
        "l2_class": "金属新材料",
        "l3_class": "",
    },
    {
        "class_code": "240201",
        "l1_class": "有色金属",
        "l2_class": "金属新材料",
        "l3_class": "其他金属新材料",
    },
    {
        "class_code": "240202",
        "l1_class": "有色金属",
        "l2_class": "金属新材料",
        "l3_class": "磁性材料",
    },
    {
        "class_code": "240300",
        "l1_class": "有色金属",
        "l2_class": "工业金属",
        "l3_class": "",
    },
    {
        "class_code": "240301",
        "l1_class": "有色金属",
        "l2_class": "工业金属",
        "l3_class": "铝",
    },
    {
        "class_code": "240302",
        "l1_class": "有色金属",
        "l2_class": "工业金属",
        "l3_class": "铜",
    },
    {
        "class_code": "240303",
        "l1_class": "有色金属",
        "l2_class": "工业金属",
        "l3_class": "铅锌",
    },
    {
        "class_code": "240400",
        "l1_class": "有色金属",
        "l2_class": "贵金属",
        "l3_class": "",
    },
    {
        "class_code": "240401",
        "l1_class": "有色金属",
        "l2_class": "贵金属",
        "l3_class": "黄金",
    },
    {
        "class_code": "240402",
        "l1_class": "有色金属",
        "l2_class": "贵金属",
        "l3_class": "白银",
    },
    {
        "class_code": "240500",
        "l1_class": "有色金属",
        "l2_class": "小金属",
        "l3_class": "",
    },
    {
        "class_code": "240501",
        "l1_class": "有色金属",
        "l2_class": "小金属",
        "l3_class": "稀土",
    },
    {
        "class_code": "240502",
        "l1_class": "有色金属",
        "l2_class": "小金属",
        "l3_class": "钨",
    },
    {
        "class_code": "240504",
        "l1_class": "有色金属",
        "l2_class": "小金属",
        "l3_class": "其他小金属",
    },
    {
        "class_code": "240505",
        "l1_class": "有色金属",
        "l2_class": "小金属",
        "l3_class": "钼",
    },
    {
        "class_code": "240600",
        "l1_class": "有色金属",
        "l2_class": "能源金属",
        "l3_class": "",
    },
    {
        "class_code": "240601",
        "l1_class": "有色金属",
        "l2_class": "能源金属",
        "l3_class": "钴",
    },
    {
        "class_code": "240602",
        "l1_class": "有色金属",
        "l2_class": "能源金属",
        "l3_class": "镍",
    },
    {
        "class_code": "240603",
        "l1_class": "有色金属",
        "l2_class": "能源金属",
        "l3_class": "锂",
    },
    {"class_code": "270000", "l1_class": "电子", "l2_class": "", "l3_class": ""},
    {
        "class_code": "270100",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "",
    },
    {
        "class_code": "270102",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "分立器件",
    },
    {
        "class_code": "270103",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "半导体材料",
    },
    {
        "class_code": "270104",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "数字芯片设计",
    },
    {
        "class_code": "270105",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "模拟芯片设计",
    },
    {
        "class_code": "270106",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "集成电路制造",
    },
    {
        "class_code": "270107",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "集成电路封测",
    },
    {
        "class_code": "270108",
        "l1_class": "电子",
        "l2_class": "半导体",
        "l3_class": "半导体设备",
    },
    {
        "class_code": "270200",
        "l1_class": "电子",
        "l2_class": "元件",
        "l3_class": "",
    },
    {
        "class_code": "270202",
        "l1_class": "电子",
        "l2_class": "元件",
        "l3_class": "印制电路板",
    },
    {
        "class_code": "270203",
        "l1_class": "电子",
        "l2_class": "元件",
        "l3_class": "被动元件",
    },
    {
        "class_code": "270300",
        "l1_class": "电子",
        "l2_class": "光学光电子",
        "l3_class": "",
    },
    {
        "class_code": "270301",
        "l1_class": "电子",
        "l2_class": "光学光电子",
        "l3_class": "面板",
    },
    {
        "class_code": "270302",
        "l1_class": "电子",
        "l2_class": "光学光电子",
        "l3_class": "LED",
    },
    {
        "class_code": "270303",
        "l1_class": "电子",
        "l2_class": "光学光电子",
        "l3_class": "光学元件",
    },
    {
        "class_code": "270400",
        "l1_class": "电子",
        "l2_class": "其他电子Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "270401",
        "l1_class": "电子",
        "l2_class": "其他电子Ⅱ",
        "l3_class": "其他电子Ⅲ",
    },
    {
        "class_code": "270500",
        "l1_class": "电子",
        "l2_class": "消费电子",
        "l3_class": "",
    },
    {
        "class_code": "270503",
        "l1_class": "电子",
        "l2_class": "消费电子",
        "l3_class": "品牌消费电子",
    },
    {
        "class_code": "270504",
        "l1_class": "电子",
        "l2_class": "消费电子",
        "l3_class": "消费电子零部件及组装",
    },
    {
        "class_code": "270600",
        "l1_class": "电子",
        "l2_class": "电子化学品Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "270601",
        "l1_class": "电子",
        "l2_class": "电子化学品Ⅱ",
        "l3_class": "电子化学品Ⅲ",
    },
    {"class_code": "280000", "l1_class": "汽车", "l2_class": "", "l3_class": ""},
    {
        "class_code": "280601",
        "l1_class": "汽车",
        "l2_class": "商用车",
        "l3_class": "商用载货车",
    },
    {
        "class_code": "280602",
        "l1_class": "汽车",
        "l2_class": "商用车",
        "l3_class": "商用载客车",
    },
    {
        "class_code": "280200",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "",
    },
    {
        "class_code": "280202",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "车身附件及饰件",
    },
    {
        "class_code": "280203",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "底盘与发动机系统",
    },
    {
        "class_code": "280204",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "轮胎轮毂",
    },
    {
        "class_code": "280205",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "其他汽车零部件",
    },
    {
        "class_code": "280206",
        "l1_class": "汽车",
        "l2_class": "汽车零部件",
        "l3_class": "汽车电子电气系统",
    },
    {
        "class_code": "280300",
        "l1_class": "汽车",
        "l2_class": "汽车服务",
        "l3_class": "",
    },
    {
        "class_code": "280302",
        "l1_class": "汽车",
        "l2_class": "汽车服务",
        "l3_class": "汽车经销商",
    },
    {
        "class_code": "280303",
        "l1_class": "汽车",
        "l2_class": "汽车服务",
        "l3_class": "汽车综合服务",
    },
    {
        "class_code": "280400",
        "l1_class": "汽车",
        "l2_class": "摩托车及其他",
        "l3_class": "",
    },
    {
        "class_code": "280401",
        "l1_class": "汽车",
        "l2_class": "摩托车及其他",
        "l3_class": "其他运输设备",
    },
    {
        "class_code": "280402",
        "l1_class": "汽车",
        "l2_class": "摩托车及其他",
        "l3_class": "摩托车",
    },
    {
        "class_code": "280500",
        "l1_class": "汽车",
        "l2_class": "乘用车",
        "l3_class": "",
    },
    {
        "class_code": "280501",
        "l1_class": "汽车",
        "l2_class": "乘用车",
        "l3_class": "电动乘用车",
    },
    {
        "class_code": "280502",
        "l1_class": "汽车",
        "l2_class": "乘用车",
        "l3_class": "综合乘用车",
    },
    {
        "class_code": "280600",
        "l1_class": "汽车",
        "l2_class": "商用车",
        "l3_class": "",
    },
    {
        "class_code": "330000",
        "l1_class": "家用电器",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "330100",
        "l1_class": "家用电器",
        "l2_class": "白色家电",
        "l3_class": "",
    },
    {
        "class_code": "330102",
        "l1_class": "家用电器",
        "l2_class": "白色家电",
        "l3_class": "空调",
    },
    {
        "class_code": "330106",
        "l1_class": "家用电器",
        "l2_class": "白色家电",
        "l3_class": "冰洗",
    },
    {
        "class_code": "330200",
        "l1_class": "家用电器",
        "l2_class": "黑色家电",
        "l3_class": "",
    },
    {
        "class_code": "330201",
        "l1_class": "家用电器",
        "l2_class": "黑色家电",
        "l3_class": "彩电",
    },
    {
        "class_code": "330202",
        "l1_class": "家用电器",
        "l2_class": "黑色家电",
        "l3_class": "其他黑色家电",
    },
    {
        "class_code": "330300",
        "l1_class": "家用电器",
        "l2_class": "小家电",
        "l3_class": "",
    },
    {
        "class_code": "330301",
        "l1_class": "家用电器",
        "l2_class": "小家电",
        "l3_class": "厨房小家电",
    },
    {
        "class_code": "330302",
        "l1_class": "家用电器",
        "l2_class": "小家电",
        "l3_class": "清洁小家电",
    },
    {
        "class_code": "330303",
        "l1_class": "家用电器",
        "l2_class": "小家电",
        "l3_class": "个护小家电",
    },
    {
        "class_code": "330400",
        "l1_class": "家用电器",
        "l2_class": "厨卫电器",
        "l3_class": "",
    },
    {
        "class_code": "330401",
        "l1_class": "家用电器",
        "l2_class": "厨卫电器",
        "l3_class": "厨房电器",
    },
    {
        "class_code": "330402",
        "l1_class": "家用电器",
        "l2_class": "厨卫电器",
        "l3_class": "卫浴电器",
    },
    {
        "class_code": "330500",
        "l1_class": "家用电器",
        "l2_class": "照明设备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "330501",
        "l1_class": "家用电器",
        "l2_class": "照明设备Ⅱ",
        "l3_class": "照明设备Ⅲ",
    },
    {
        "class_code": "330600",
        "l1_class": "家用电器",
        "l2_class": "家电零部件Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "330601",
        "l1_class": "家用电器",
        "l2_class": "家电零部件Ⅱ",
        "l3_class": "家电零部件Ⅲ",
    },
    {
        "class_code": "330700",
        "l1_class": "家用电器",
        "l2_class": "其他家电Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "330701",
        "l1_class": "家用电器",
        "l2_class": "其他家电Ⅱ",
        "l3_class": "其他家电Ⅲ",
    },
    {
        "class_code": "340000",
        "l1_class": "食品饮料",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "340400",
        "l1_class": "食品饮料",
        "l2_class": "食品加工",
        "l3_class": "",
    },
    {
        "class_code": "340401",
        "l1_class": "食品饮料",
        "l2_class": "食品加工",
        "l3_class": "肉制品",
    },
    {
        "class_code": "340404",
        "l1_class": "食品饮料",
        "l2_class": "食品加工",
        "l3_class": "其他食品",
    },
    {
        "class_code": "340406",
        "l1_class": "食品饮料",
        "l2_class": "食品加工",
        "l3_class": "预加工食品",
    },
    {
        "class_code": "340407",
        "l1_class": "食品饮料",
        "l2_class": "食品加工",
        "l3_class": "保健品",
    },
    {
        "class_code": "340500",
        "l1_class": "食品饮料",
        "l2_class": "白酒Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "340501",
        "l1_class": "食品饮料",
        "l2_class": "白酒Ⅱ",
        "l3_class": "白酒Ⅲ",
    },
    {
        "class_code": "340600",
        "l1_class": "食品饮料",
        "l2_class": "非白酒",
        "l3_class": "",
    },
    {
        "class_code": "340601",
        "l1_class": "食品饮料",
        "l2_class": "非白酒",
        "l3_class": "啤酒",
    },
    {
        "class_code": "340602",
        "l1_class": "食品饮料",
        "l2_class": "非白酒",
        "l3_class": "其他酒类",
    },
    {
        "class_code": "340700",
        "l1_class": "食品饮料",
        "l2_class": "饮料乳品",
        "l3_class": "",
    },
    {
        "class_code": "340701",
        "l1_class": "食品饮料",
        "l2_class": "饮料乳品",
        "l3_class": "软饮料",
    },
    {
        "class_code": "340702",
        "l1_class": "食品饮料",
        "l2_class": "饮料乳品",
        "l3_class": "乳品",
    },
    {
        "class_code": "340800",
        "l1_class": "食品饮料",
        "l2_class": "休闲食品",
        "l3_class": "",
    },
    {
        "class_code": "340801",
        "l1_class": "食品饮料",
        "l2_class": "休闲食品",
        "l3_class": "零食",
    },
    {
        "class_code": "340802",
        "l1_class": "食品饮料",
        "l2_class": "休闲食品",
        "l3_class": "烘焙食品",
    },
    {
        "class_code": "340803",
        "l1_class": "食品饮料",
        "l2_class": "休闲食品",
        "l3_class": "熟食",
    },
    {
        "class_code": "340900",
        "l1_class": "食品饮料",
        "l2_class": "调味发酵品Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "340901",
        "l1_class": "食品饮料",
        "l2_class": "调味发酵品Ⅱ",
        "l3_class": "调味发酵品Ⅲ",
    },
    {
        "class_code": "350000",
        "l1_class": "纺织服饰",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "350100",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "",
    },
    {
        "class_code": "350102",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "棉纺",
    },
    {
        "class_code": "350104",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "印染",
    },
    {
        "class_code": "350105",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "辅料",
    },
    {
        "class_code": "350106",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "其他纺织",
    },
    {
        "class_code": "350107",
        "l1_class": "纺织服饰",
        "l2_class": "纺织制造",
        "l3_class": "纺织鞋类制造",
    },
    {
        "class_code": "350200",
        "l1_class": "纺织服饰",
        "l2_class": "服装家纺",
        "l3_class": "",
    },
    {
        "class_code": "350205",
        "l1_class": "纺织服饰",
        "l2_class": "服装家纺",
        "l3_class": "鞋帽及其他",
    },
    {
        "class_code": "350206",
        "l1_class": "纺织服饰",
        "l2_class": "服装家纺",
        "l3_class": "家纺",
    },
    {
        "class_code": "350208",
        "l1_class": "纺织服饰",
        "l2_class": "服装家纺",
        "l3_class": "运动服装",
    },
    {
        "class_code": "350209",
        "l1_class": "纺织服饰",
        "l2_class": "服装家纺",
        "l3_class": "非运动服装",
    },
    {
        "class_code": "350300",
        "l1_class": "纺织服饰",
        "l2_class": "饰品",
        "l3_class": "",
    },
    {
        "class_code": "350301",
        "l1_class": "纺织服饰",
        "l2_class": "饰品",
        "l3_class": "钟表珠宝",
    },
    {
        "class_code": "350302",
        "l1_class": "纺织服饰",
        "l2_class": "饰品",
        "l3_class": "多品类奢侈品",
    },
    {
        "class_code": "350303",
        "l1_class": "纺织服饰",
        "l2_class": "饰品",
        "l3_class": "其他饰品",
    },
    {
        "class_code": "360000",
        "l1_class": "轻工制造",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "360100",
        "l1_class": "轻工制造",
        "l2_class": "造纸",
        "l3_class": "",
    },
    {
        "class_code": "360102",
        "l1_class": "轻工制造",
        "l2_class": "造纸",
        "l3_class": "大宗用纸",
    },
    {
        "class_code": "360103",
        "l1_class": "轻工制造",
        "l2_class": "造纸",
        "l3_class": "特种纸",
    },
    {
        "class_code": "360200",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "",
    },
    {
        "class_code": "360202",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "印刷",
    },
    {
        "class_code": "360203",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "金属包装",
    },
    {
        "class_code": "360204",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "塑料包装",
    },
    {
        "class_code": "360205",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "纸包装",
    },
    {
        "class_code": "360206",
        "l1_class": "轻工制造",
        "l2_class": "包装印刷",
        "l3_class": "综合包装",
    },
    {
        "class_code": "360300",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "",
    },
    {
        "class_code": "360306",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "瓷砖地板",
    },
    {
        "class_code": "360307",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "成品家居",
    },
    {
        "class_code": "360308",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "定制家居",
    },
    {
        "class_code": "360309",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "卫浴制品",
    },
    {
        "class_code": "360311",
        "l1_class": "轻工制造",
        "l2_class": "家居用品",
        "l3_class": "其他家居用品",
    },
    {
        "class_code": "360500",
        "l1_class": "轻工制造",
        "l2_class": "文娱用品",
        "l3_class": "",
    },
    {
        "class_code": "360501",
        "l1_class": "轻工制造",
        "l2_class": "文娱用品",
        "l3_class": "文化用品",
    },
    {
        "class_code": "360502",
        "l1_class": "轻工制造",
        "l2_class": "文娱用品",
        "l3_class": "娱乐用品",
    },
    {
        "class_code": "370000",
        "l1_class": "医药生物",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "370100",
        "l1_class": "医药生物",
        "l2_class": "化学制药",
        "l3_class": "",
    },
    {
        "class_code": "370101",
        "l1_class": "医药生物",
        "l2_class": "化学制药",
        "l3_class": "原料药",
    },
    {
        "class_code": "370102",
        "l1_class": "医药生物",
        "l2_class": "化学制药",
        "l3_class": "化学制剂",
    },
    {
        "class_code": "370200",
        "l1_class": "医药生物",
        "l2_class": "中药Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "370201",
        "l1_class": "医药生物",
        "l2_class": "中药Ⅱ",
        "l3_class": "中药Ⅲ",
    },
    {
        "class_code": "370300",
        "l1_class": "医药生物",
        "l2_class": "生物制品",
        "l3_class": "",
    },
    {
        "class_code": "370302",
        "l1_class": "医药生物",
        "l2_class": "生物制品",
        "l3_class": "血液制品",
    },
    {
        "class_code": "370303",
        "l1_class": "医药生物",
        "l2_class": "生物制品",
        "l3_class": "疫苗",
    },
    {
        "class_code": "370304",
        "l1_class": "医药生物",
        "l2_class": "生物制品",
        "l3_class": "其他生物制品",
    },
    {
        "class_code": "370400",
        "l1_class": "医药生物",
        "l2_class": "医药商业",
        "l3_class": "",
    },
    {
        "class_code": "370402",
        "l1_class": "医药生物",
        "l2_class": "医药商业",
        "l3_class": "医药流通",
    },
    {
        "class_code": "370403",
        "l1_class": "医药生物",
        "l2_class": "医药商业",
        "l3_class": "线下药店",
    },
    {
        "class_code": "370404",
        "l1_class": "医药生物",
        "l2_class": "医药商业",
        "l3_class": "互联网药店",
    },
    {
        "class_code": "370500",
        "l1_class": "医药生物",
        "l2_class": "医疗器械",
        "l3_class": "",
    },
    {
        "class_code": "370502",
        "l1_class": "医药生物",
        "l2_class": "医疗器械",
        "l3_class": "医疗设备",
    },
    {
        "class_code": "370503",
        "l1_class": "医药生物",
        "l2_class": "医疗器械",
        "l3_class": "医疗耗材",
    },
    {
        "class_code": "370504",
        "l1_class": "医药生物",
        "l2_class": "医疗器械",
        "l3_class": "体外诊断",
    },
    {
        "class_code": "370600",
        "l1_class": "医药生物",
        "l2_class": "医疗服务",
        "l3_class": "",
    },
    {
        "class_code": "370602",
        "l1_class": "医药生物",
        "l2_class": "医疗服务",
        "l3_class": "诊断服务",
    },
    {
        "class_code": "370603",
        "l1_class": "医药生物",
        "l2_class": "医疗服务",
        "l3_class": "医疗研发外包",
    },
    {
        "class_code": "370604",
        "l1_class": "医药生物",
        "l2_class": "医疗服务",
        "l3_class": "医院",
    },
    {
        "class_code": "370605",
        "l1_class": "医药生物",
        "l2_class": "医疗服务",
        "l3_class": "其他医疗服务",
    },
    {
        "class_code": "410000",
        "l1_class": "公用事业",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "410100",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "",
    },
    {
        "class_code": "410101",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "火力发电",
    },
    {
        "class_code": "410102",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "水力发电",
    },
    {
        "class_code": "410104",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "热力服务",
    },
    {
        "class_code": "410106",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "光伏发电",
    },
    {
        "class_code": "410107",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "风力发电",
    },
    {
        "class_code": "410108",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "核力发电",
    },
    {
        "class_code": "410109",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "其他能源发电",
    },
    {
        "class_code": "410110",
        "l1_class": "公用事业",
        "l2_class": "电力",
        "l3_class": "电能综合服务",
    },
    {
        "class_code": "410300",
        "l1_class": "公用事业",
        "l2_class": "燃气Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "410301",
        "l1_class": "公用事业",
        "l2_class": "燃气Ⅱ",
        "l3_class": "燃气Ⅲ",
    },
    {
        "class_code": "420000",
        "l1_class": "交通运输",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "420800",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "",
    },
    {
        "class_code": "420802",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "原材料供应链服务",
    },
    {
        "class_code": "420803",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "中间产品及消费品供应链服务",
    },
    {
        "class_code": "420804",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "快递",
    },
    {
        "class_code": "420805",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "跨境物流",
    },
    {
        "class_code": "420806",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "仓储物流",
    },
    {
        "class_code": "420807",
        "l1_class": "交通运输",
        "l2_class": "物流",
        "l3_class": "公路货运",
    },
    {
        "class_code": "420900",
        "l1_class": "交通运输",
        "l2_class": "铁路公路",
        "l3_class": "",
    },
    {
        "class_code": "420901",
        "l1_class": "交通运输",
        "l2_class": "铁路公路",
        "l3_class": "高速公路",
    },
    {
        "class_code": "420902",
        "l1_class": "交通运输",
        "l2_class": "铁路公路",
        "l3_class": "公交",
    },
    {
        "class_code": "420903",
        "l1_class": "交通运输",
        "l2_class": "铁路公路",
        "l3_class": "铁路运输",
    },
    {
        "class_code": "421000",
        "l1_class": "交通运输",
        "l2_class": "航空机场",
        "l3_class": "",
    },
    {
        "class_code": "421001",
        "l1_class": "交通运输",
        "l2_class": "航空机场",
        "l3_class": "航空运输",
    },
    {
        "class_code": "421002",
        "l1_class": "交通运输",
        "l2_class": "航空机场",
        "l3_class": "机场",
    },
    {
        "class_code": "421100",
        "l1_class": "交通运输",
        "l2_class": "航运港口",
        "l3_class": "",
    },
    {
        "class_code": "421101",
        "l1_class": "交通运输",
        "l2_class": "航运港口",
        "l3_class": "航运",
    },
    {
        "class_code": "421102",
        "l1_class": "交通运输",
        "l2_class": "航运港口",
        "l3_class": "港口",
    },
    {"class_code": "430000", "l1_class": "房地产", "l2_class": "", "l3_class": ""},
    {
        "class_code": "430100",
        "l1_class": "房地产",
        "l2_class": "房地产开发",
        "l3_class": "",
    },
    {
        "class_code": "430101",
        "l1_class": "房地产",
        "l2_class": "房地产开发",
        "l3_class": "住宅开发",
    },
    {
        "class_code": "430102",
        "l1_class": "房地产",
        "l2_class": "房地产开发",
        "l3_class": "商业地产",
    },
    {
        "class_code": "430103",
        "l1_class": "房地产",
        "l2_class": "房地产开发",
        "l3_class": "产业地产",
    },
    {
        "class_code": "430300",
        "l1_class": "房地产",
        "l2_class": "房地产服务",
        "l3_class": "",
    },
    {
        "class_code": "430301",
        "l1_class": "房地产",
        "l2_class": "房地产服务",
        "l3_class": "物业管理",
    },
    {
        "class_code": "430302",
        "l1_class": "房地产",
        "l2_class": "房地产服务",
        "l3_class": "房产租赁经纪",
    },
    {
        "class_code": "430303",
        "l1_class": "房地产",
        "l2_class": "房地产服务",
        "l3_class": "房地产综合服务",
    },
    {
        "class_code": "450000",
        "l1_class": "商贸零售",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "450200",
        "l1_class": "商贸零售",
        "l2_class": "贸易Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "450201",
        "l1_class": "商贸零售",
        "l2_class": "贸易Ⅱ",
        "l3_class": "贸易Ⅲ",
    },
    {
        "class_code": "450300",
        "l1_class": "商贸零售",
        "l2_class": "一般零售",
        "l3_class": "",
    },
    {
        "class_code": "450301",
        "l1_class": "商贸零售",
        "l2_class": "一般零售",
        "l3_class": "百货",
    },
    {
        "class_code": "450302",
        "l1_class": "商贸零售",
        "l2_class": "一般零售",
        "l3_class": "超市",
    },
    {
        "class_code": "450303",
        "l1_class": "商贸零售",
        "l2_class": "一般零售",
        "l3_class": "多业态零售",
    },
    {
        "class_code": "450304",
        "l1_class": "商贸零售",
        "l2_class": "一般零售",
        "l3_class": "商业物业经营",
    },
    {
        "class_code": "450400",
        "l1_class": "商贸零售",
        "l2_class": "专业连锁Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "450401",
        "l1_class": "商贸零售",
        "l2_class": "专业连锁Ⅱ",
        "l3_class": "专业连锁Ⅲ",
    },
    {
        "class_code": "450600",
        "l1_class": "商贸零售",
        "l2_class": "互联网电商",
        "l3_class": "",
    },
    {
        "class_code": "450601",
        "l1_class": "商贸零售",
        "l2_class": "互联网电商",
        "l3_class": "综合电商",
    },
    {
        "class_code": "450602",
        "l1_class": "商贸零售",
        "l2_class": "互联网电商",
        "l3_class": "跨境电商",
    },
    {
        "class_code": "450603",
        "l1_class": "商贸零售",
        "l2_class": "互联网电商",
        "l3_class": "电商服务",
    },
    {
        "class_code": "450700",
        "l1_class": "商贸零售",
        "l2_class": "旅游零售Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "450701",
        "l1_class": "商贸零售",
        "l2_class": "旅游零售Ⅱ",
        "l3_class": "旅游零售Ⅲ",
    },
    {
        "class_code": "460000",
        "l1_class": "社会服务",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "460600",
        "l1_class": "社会服务",
        "l2_class": "体育Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "460601",
        "l1_class": "社会服务",
        "l2_class": "体育Ⅱ",
        "l3_class": "体育Ⅲ",
    },
    {
        "class_code": "460700",
        "l1_class": "社会服务",
        "l2_class": "本地生活服务Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "460701",
        "l1_class": "社会服务",
        "l2_class": "本地生活服务Ⅱ",
        "l3_class": "本地生活服务Ⅲ",
    },
    {
        "class_code": "460800",
        "l1_class": "社会服务",
        "l2_class": "专业服务",
        "l3_class": "",
    },
    {
        "class_code": "460801",
        "l1_class": "社会服务",
        "l2_class": "专业服务",
        "l3_class": "人力资源服务",
    },
    {
        "class_code": "460802",
        "l1_class": "社会服务",
        "l2_class": "专业服务",
        "l3_class": "检测服务",
    },
    {
        "class_code": "460803",
        "l1_class": "社会服务",
        "l2_class": "专业服务",
        "l3_class": "会展服务",
    },
    {
        "class_code": "460804",
        "l1_class": "社会服务",
        "l2_class": "专业服务",
        "l3_class": "其他专业服务",
    },
    {
        "class_code": "460900",
        "l1_class": "社会服务",
        "l2_class": "酒店餐饮",
        "l3_class": "",
    },
    {
        "class_code": "460901",
        "l1_class": "社会服务",
        "l2_class": "酒店餐饮",
        "l3_class": "酒店",
    },
    {
        "class_code": "460902",
        "l1_class": "社会服务",
        "l2_class": "酒店餐饮",
        "l3_class": "餐饮",
    },
    {
        "class_code": "461000",
        "l1_class": "社会服务",
        "l2_class": "旅游及景区",
        "l3_class": "",
    },
    {
        "class_code": "461001",
        "l1_class": "社会服务",
        "l2_class": "旅游及景区",
        "l3_class": "博彩",
    },
    {
        "class_code": "461002",
        "l1_class": "社会服务",
        "l2_class": "旅游及景区",
        "l3_class": "人工景区",
    },
    {
        "class_code": "461003",
        "l1_class": "社会服务",
        "l2_class": "旅游及景区",
        "l3_class": "自然景区",
    },
    {
        "class_code": "461004",
        "l1_class": "社会服务",
        "l2_class": "旅游及景区",
        "l3_class": "旅游综合",
    },
    {
        "class_code": "461100",
        "l1_class": "社会服务",
        "l2_class": "教育",
        "l3_class": "",
    },
    {
        "class_code": "461101",
        "l1_class": "社会服务",
        "l2_class": "教育",
        "l3_class": "学历教育",
    },
    {
        "class_code": "461102",
        "l1_class": "社会服务",
        "l2_class": "教育",
        "l3_class": "培训教育",
    },
    {
        "class_code": "461103",
        "l1_class": "社会服务",
        "l2_class": "教育",
        "l3_class": "教育运营及其他",
    },
    {"class_code": "480000", "l1_class": "银行", "l2_class": "", "l3_class": ""},
    {
        "class_code": "480200",
        "l1_class": "银行",
        "l2_class": "国有大型银行Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "480201",
        "l1_class": "银行",
        "l2_class": "国有大型银行Ⅱ",
        "l3_class": "国有大型银行Ⅲ",
    },
    {
        "class_code": "480300",
        "l1_class": "银行",
        "l2_class": "股份制银行Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "480301",
        "l1_class": "银行",
        "l2_class": "股份制银行Ⅱ",
        "l3_class": "股份制银行Ⅲ",
    },
    {
        "class_code": "480400",
        "l1_class": "银行",
        "l2_class": "城商行Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "480401",
        "l1_class": "银行",
        "l2_class": "城商行Ⅱ",
        "l3_class": "城商行Ⅲ",
    },
    {
        "class_code": "480500",
        "l1_class": "银行",
        "l2_class": "农商行Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "480501",
        "l1_class": "银行",
        "l2_class": "农商行Ⅱ",
        "l3_class": "农商行Ⅲ",
    },
    {
        "class_code": "480600",
        "l1_class": "银行",
        "l2_class": "其他银行Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "480601",
        "l1_class": "银行",
        "l2_class": "其他银行Ⅱ",
        "l3_class": "其他银行Ⅲ",
    },
    {
        "class_code": "490000",
        "l1_class": "非银金融",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "490100",
        "l1_class": "非银金融",
        "l2_class": "证券Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "490101",
        "l1_class": "非银金融",
        "l2_class": "证券Ⅱ",
        "l3_class": "证券Ⅲ",
    },
    {
        "class_code": "490200",
        "l1_class": "非银金融",
        "l2_class": "保险Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "490201",
        "l1_class": "非银金融",
        "l2_class": "保险Ⅱ",
        "l3_class": "保险Ⅲ",
    },
    {
        "class_code": "490300",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "",
    },
    {
        "class_code": "490302",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "金融控股",
    },
    {
        "class_code": "490303",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "期货",
    },
    {
        "class_code": "490304",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "信托",
    },
    {
        "class_code": "490305",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "租赁",
    },
    {
        "class_code": "490306",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "金融信息服务",
    },
    {
        "class_code": "490307",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "资产管理",
    },
    {
        "class_code": "490308",
        "l1_class": "非银金融",
        "l2_class": "多元金融",
        "l3_class": "其他多元金融",
    },
    {"class_code": "510000", "l1_class": "综合", "l2_class": "", "l3_class": ""},
    {
        "class_code": "510100",
        "l1_class": "综合",
        "l2_class": "综合Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "510101",
        "l1_class": "综合",
        "l2_class": "综合Ⅱ",
        "l3_class": "综合Ⅲ",
    },
    {
        "class_code": "610000",
        "l1_class": "建筑材料",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "610100",
        "l1_class": "建筑材料",
        "l2_class": "水泥",
        "l3_class": "",
    },
    {
        "class_code": "610101",
        "l1_class": "建筑材料",
        "l2_class": "水泥",
        "l3_class": "水泥制造",
    },
    {
        "class_code": "610102",
        "l1_class": "建筑材料",
        "l2_class": "水泥",
        "l3_class": "水泥制品",
    },
    {
        "class_code": "610200",
        "l1_class": "建筑材料",
        "l2_class": "玻璃玻纤",
        "l3_class": "",
    },
    {
        "class_code": "610201",
        "l1_class": "建筑材料",
        "l2_class": "玻璃玻纤",
        "l3_class": "玻璃制造",
    },
    {
        "class_code": "610202",
        "l1_class": "建筑材料",
        "l2_class": "玻璃玻纤",
        "l3_class": "玻纤制造",
    },
    {
        "class_code": "610300",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "",
    },
    {
        "class_code": "610301",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "耐火材料",
    },
    {
        "class_code": "610302",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "管材",
    },
    {
        "class_code": "610303",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "其他建材",
    },
    {
        "class_code": "610304",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "防水材料",
    },
    {
        "class_code": "610305",
        "l1_class": "建筑材料",
        "l2_class": "装修建材",
        "l3_class": "涂料",
    },
    {
        "class_code": "620000",
        "l1_class": "建筑装饰",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "620100",
        "l1_class": "建筑装饰",
        "l2_class": "房屋建设Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "620101",
        "l1_class": "建筑装饰",
        "l2_class": "房屋建设Ⅱ",
        "l3_class": "房屋建设Ⅲ",
    },
    {
        "class_code": "620200",
        "l1_class": "建筑装饰",
        "l2_class": "装修装饰Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "620201",
        "l1_class": "建筑装饰",
        "l2_class": "装修装饰Ⅱ",
        "l3_class": "装修装饰Ⅲ",
    },
    {
        "class_code": "620300",
        "l1_class": "建筑装饰",
        "l2_class": "基础建设",
        "l3_class": "",
    },
    {
        "class_code": "620306",
        "l1_class": "建筑装饰",
        "l2_class": "基础建设",
        "l3_class": "基建市政工程",
    },
    {
        "class_code": "620307",
        "l1_class": "建筑装饰",
        "l2_class": "基础建设",
        "l3_class": "园林工程",
    },
    {
        "class_code": "620400",
        "l1_class": "建筑装饰",
        "l2_class": "专业工程",
        "l3_class": "",
    },
    {
        "class_code": "620401",
        "l1_class": "建筑装饰",
        "l2_class": "专业工程",
        "l3_class": "钢结构",
    },
    {
        "class_code": "620402",
        "l1_class": "建筑装饰",
        "l2_class": "专业工程",
        "l3_class": "化学工程",
    },
    {
        "class_code": "620403",
        "l1_class": "建筑装饰",
        "l2_class": "专业工程",
        "l3_class": "国际工程",
    },
    {
        "class_code": "620404",
        "l1_class": "建筑装饰",
        "l2_class": "专业工程",
        "l3_class": "其他专业工程",
    },
    {
        "class_code": "620600",
        "l1_class": "建筑装饰",
        "l2_class": "工程咨询服务Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "620601",
        "l1_class": "建筑装饰",
        "l2_class": "工程咨询服务Ⅱ",
        "l3_class": "工程咨询服务Ⅲ",
    },
    {
        "class_code": "630000",
        "l1_class": "电力设备",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "630100",
        "l1_class": "电力设备",
        "l2_class": "电机Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "630101",
        "l1_class": "电力设备",
        "l2_class": "电机Ⅱ",
        "l3_class": "电机Ⅲ",
    },
    {
        "class_code": "630300",
        "l1_class": "电力设备",
        "l2_class": "其他电源设备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "630301",
        "l1_class": "电力设备",
        "l2_class": "其他电源设备Ⅱ",
        "l3_class": "综合电力设备商",
    },
    {
        "class_code": "630304",
        "l1_class": "电力设备",
        "l2_class": "其他电源设备Ⅱ",
        "l3_class": "火电设备",
    },
    {
        "class_code": "630306",
        "l1_class": "电力设备",
        "l2_class": "其他电源设备Ⅱ",
        "l3_class": "其他电源设备�III",
    },
    {
        "class_code": "630500",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "",
    },
    {
        "class_code": "630501",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "硅料硅片",
    },
    {
        "class_code": "630502",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "光伏电池组件",
    },
    {
        "class_code": "630503",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "逆变器",
    },
    {
        "class_code": "630504",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "光伏辅材",
    },
    {
        "class_code": "630505",
        "l1_class": "电力设备",
        "l2_class": "光伏设备",
        "l3_class": "光伏加工设备",
    },
    {
        "class_code": "630600",
        "l1_class": "电力设备",
        "l2_class": "风电设备",
        "l3_class": "",
    },
    {
        "class_code": "630601",
        "l1_class": "电力设备",
        "l2_class": "风电设备",
        "l3_class": "风电整机",
    },
    {
        "class_code": "630602",
        "l1_class": "电力设备",
        "l2_class": "风电设备",
        "l3_class": "风电零部件",
    },
    {
        "class_code": "630700",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "",
    },
    {
        "class_code": "630701",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "锂电池",
    },
    {
        "class_code": "630702",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "电池化学品",
    },
    {
        "class_code": "630703",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "锂电专用设备",
    },
    {
        "class_code": "630704",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "燃料电池",
    },
    {
        "class_code": "630705",
        "l1_class": "电力设备",
        "l2_class": "电池",
        "l3_class": "蓄电池及其他电池",
    },
    {
        "class_code": "630800",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "",
    },
    {
        "class_code": "630801",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "输变电设备",
    },
    {
        "class_code": "630802",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "配电设备",
    },
    {
        "class_code": "630803",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "电网自动化设备",
    },
    {
        "class_code": "630804",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "电工仪器仪表",
    },
    {
        "class_code": "630805",
        "l1_class": "电力设备",
        "l2_class": "电网设备",
        "l3_class": "线缆部件及其他",
    },
    {
        "class_code": "640000",
        "l1_class": "机械设备",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "640100",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "",
    },
    {
        "class_code": "640101",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "机床工具",
    },
    {
        "class_code": "640103",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "磨具磨料",
    },
    {
        "class_code": "640105",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "制冷空调设备",
    },
    {
        "class_code": "640106",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "其他通用设备",
    },
    {
        "class_code": "640107",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "仪器仪表",
    },
    {
        "class_code": "640108",
        "l1_class": "机械设备",
        "l2_class": "通用设备",
        "l3_class": "金属制品",
    },
    {
        "class_code": "640200",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "",
    },
    {
        "class_code": "640203",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "能源及重型设备",
    },
    {
        "class_code": "640204",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "楼宇设备",
    },
    {
        "class_code": "640206",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "纺织服装设备",
    },
    {
        "class_code": "640207",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "农用机械",
    },
    {
        "class_code": "640208",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "印刷包装机械",
    },
    {
        "class_code": "640209",
        "l1_class": "机械设备",
        "l2_class": "专用设备",
        "l3_class": "其他专用设备",
    },
    {
        "class_code": "640500",
        "l1_class": "机械设备",
        "l2_class": "轨交设备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "640501",
        "l1_class": "机械设备",
        "l2_class": "轨交设备Ⅱ",
        "l3_class": "轨交设备Ⅲ",
    },
    {
        "class_code": "640600",
        "l1_class": "机械设备",
        "l2_class": "工程机械",
        "l3_class": "",
    },
    {
        "class_code": "640601",
        "l1_class": "机械设备",
        "l2_class": "工程机械",
        "l3_class": "工程机械整机",
    },
    {
        "class_code": "640602",
        "l1_class": "机械设备",
        "l2_class": "工程机械",
        "l3_class": "工程机械器件",
    },
    {
        "class_code": "640700",
        "l1_class": "机械设备",
        "l2_class": "自动化设备",
        "l3_class": "",
    },
    {
        "class_code": "640701",
        "l1_class": "机械设备",
        "l2_class": "自动化设备",
        "l3_class": "机器人",
    },
    {
        "class_code": "640702",
        "l1_class": "机械设备",
        "l2_class": "自动化设备",
        "l3_class": "工控设备",
    },
    {
        "class_code": "640703",
        "l1_class": "机械设备",
        "l2_class": "自动化设备",
        "l3_class": "激光设备",
    },
    {
        "class_code": "640704",
        "l1_class": "机械设备",
        "l2_class": "自动化设备",
        "l3_class": "其他自动化设备",
    },
    {
        "class_code": "650000",
        "l1_class": "国防军工",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "650100",
        "l1_class": "国防军工",
        "l2_class": "航天装备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "650101",
        "l1_class": "国防军工",
        "l2_class": "航天装备Ⅱ",
        "l3_class": "航天装备Ⅲ",
    },
    {
        "class_code": "650200",
        "l1_class": "国防军工",
        "l2_class": "航空装备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "650201",
        "l1_class": "国防军工",
        "l2_class": "航空装备Ⅱ",
        "l3_class": "航空装备Ⅲ",
    },
    {
        "class_code": "650300",
        "l1_class": "国防军工",
        "l2_class": "地面兵装Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "650301",
        "l1_class": "国防军工",
        "l2_class": "地面兵装Ⅱ",
        "l3_class": "地面兵装Ⅲ",
    },
    {
        "class_code": "650400",
        "l1_class": "国防军工",
        "l2_class": "航海装备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "650401",
        "l1_class": "国防军工",
        "l2_class": "航海装备Ⅱ",
        "l3_class": "航海装备Ⅲ",
    },
    {
        "class_code": "650500",
        "l1_class": "国防军工",
        "l2_class": "军工电子Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "650501",
        "l1_class": "国防军工",
        "l2_class": "军工电子Ⅱ",
        "l3_class": "军工电子Ⅲ",
    },
    {"class_code": "710000", "l1_class": "计算机", "l2_class": "", "l3_class": ""},
    {
        "class_code": "710100",
        "l1_class": "计算机",
        "l2_class": "计算机设备",
        "l3_class": "",
    },
    {
        "class_code": "710102",
        "l1_class": "计算机",
        "l2_class": "计算机设备",
        "l3_class": "安防设备",
    },
    {
        "class_code": "710103",
        "l1_class": "计算机",
        "l2_class": "计算机设备",
        "l3_class": "其他计算机设备",
    },
    {
        "class_code": "710300",
        "l1_class": "计算机",
        "l2_class": "IT服务Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "710301",
        "l1_class": "计算机",
        "l2_class": "IT服务Ⅱ",
        "l3_class": "IT服务Ⅲ",
    },
    {
        "class_code": "710400",
        "l1_class": "计算机",
        "l2_class": "软件开发",
        "l3_class": "",
    },
    {
        "class_code": "710401",
        "l1_class": "计算机",
        "l2_class": "软件开发",
        "l3_class": "垂直应用软件",
    },
    {
        "class_code": "710402",
        "l1_class": "计算机",
        "l2_class": "软件开发",
        "l3_class": "横向通用软件",
    },
    {"class_code": "720000", "l1_class": "传媒", "l2_class": "", "l3_class": ""},
    {
        "class_code": "720400",
        "l1_class": "传媒",
        "l2_class": "游戏Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "720401",
        "l1_class": "传媒",
        "l2_class": "游戏Ⅱ",
        "l3_class": "游戏Ⅲ",
    },
    {
        "class_code": "720500",
        "l1_class": "传媒",
        "l2_class": "广告营销",
        "l3_class": "",
    },
    {
        "class_code": "720501",
        "l1_class": "传媒",
        "l2_class": "广告营销",
        "l3_class": "营销代理",
    },
    {
        "class_code": "720502",
        "l1_class": "传媒",
        "l2_class": "广告营销",
        "l3_class": "广告媒体",
    },
    {
        "class_code": "720600",
        "l1_class": "传媒",
        "l2_class": "影视院线",
        "l3_class": "",
    },
    {
        "class_code": "720601",
        "l1_class": "传媒",
        "l2_class": "影视院线",
        "l3_class": "影视动漫制作",
    },
    {
        "class_code": "720602",
        "l1_class": "传媒",
        "l2_class": "影视院线",
        "l3_class": "院线",
    },
    {
        "class_code": "720700",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "",
    },
    {
        "class_code": "720701",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "视频媒体",
    },
    {
        "class_code": "720702",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "音频媒体",
    },
    {
        "class_code": "720703",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "图片媒体",
    },
    {
        "class_code": "720704",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "门户网站",
    },
    {
        "class_code": "720705",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "文字媒体",
    },
    {
        "class_code": "720706",
        "l1_class": "传媒",
        "l2_class": "数字媒体",
        "l3_class": "其他数字媒体",
    },
    {
        "class_code": "720800",
        "l1_class": "传媒",
        "l2_class": "社交Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "720801",
        "l1_class": "传媒",
        "l2_class": "社交Ⅱ",
        "l3_class": "社交Ⅲ",
    },
    {
        "class_code": "720900",
        "l1_class": "传媒",
        "l2_class": "出版",
        "l3_class": "",
    },
    {
        "class_code": "720901",
        "l1_class": "传媒",
        "l2_class": "出版",
        "l3_class": "教育出版",
    },
    {
        "class_code": "720902",
        "l1_class": "传媒",
        "l2_class": "出版",
        "l3_class": "大众出版",
    },
    {
        "class_code": "720903",
        "l1_class": "传媒",
        "l2_class": "出版",
        "l3_class": "其他出版",
    },
    {
        "class_code": "721000",
        "l1_class": "传媒",
        "l2_class": "电视广播Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "721001",
        "l1_class": "传媒",
        "l2_class": "电视广播Ⅱ",
        "l3_class": "电视广播Ⅲ",
    },
    {"class_code": "730000", "l1_class": "通信", "l2_class": "", "l3_class": ""},
    {
        "class_code": "730100",
        "l1_class": "通信",
        "l2_class": "通信服务",
        "l3_class": "",
    },
    {
        "class_code": "730102",
        "l1_class": "通信",
        "l2_class": "通信服务",
        "l3_class": "电信运营商",
    },
    {
        "class_code": "730103",
        "l1_class": "通信",
        "l2_class": "通信服务",
        "l3_class": "通信工程及服务",
    },
    {
        "class_code": "730104",
        "l1_class": "通信",
        "l2_class": "通信服务",
        "l3_class": "通信应用增值服务",
    },
    {
        "class_code": "730200",
        "l1_class": "通信",
        "l2_class": "通信设备",
        "l3_class": "",
    },
    {
        "class_code": "730204",
        "l1_class": "通信",
        "l2_class": "通信设备",
        "l3_class": "通信网络设备及器件",
    },
    {
        "class_code": "730205",
        "l1_class": "通信",
        "l2_class": "通信设备",
        "l3_class": "通信线缆及配套",
    },
    {
        "class_code": "730206",
        "l1_class": "通信",
        "l2_class": "通信设备",
        "l3_class": "通信终端及配件",
    },
    {
        "class_code": "730207",
        "l1_class": "通信",
        "l2_class": "通信设备",
        "l3_class": "其他通信设备",
    },
    {"class_code": "740000", "l1_class": "煤炭", "l2_class": "", "l3_class": ""},
    {
        "class_code": "740100",
        "l1_class": "煤炭",
        "l2_class": "煤炭开采",
        "l3_class": "",
    },
    {
        "class_code": "740101",
        "l1_class": "煤炭",
        "l2_class": "煤炭开采",
        "l3_class": "动力煤",
    },
    {
        "class_code": "740102",
        "l1_class": "煤炭",
        "l2_class": "煤炭开采",
        "l3_class": "焦煤",
    },
    {
        "class_code": "740200",
        "l1_class": "煤炭",
        "l2_class": "焦炭Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "740201",
        "l1_class": "煤炭",
        "l2_class": "焦炭Ⅱ",
        "l3_class": "焦炭Ⅲ",
    },
    {
        "class_code": "750000",
        "l1_class": "石油石化",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "750100",
        "l1_class": "石油石化",
        "l2_class": "油气开采Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "750101",
        "l1_class": "石油石化",
        "l2_class": "油气开采Ⅱ",
        "l3_class": "油气开采Ⅲ",
    },
    {
        "class_code": "750200",
        "l1_class": "石油石化",
        "l2_class": "油服工程",
        "l3_class": "",
    },
    {
        "class_code": "750201",
        "l1_class": "石油石化",
        "l2_class": "油服工程",
        "l3_class": "油田服务",
    },
    {
        "class_code": "750202",
        "l1_class": "石油石化",
        "l2_class": "油服工程",
        "l3_class": "油气及炼化工程",
    },
    {
        "class_code": "750300",
        "l1_class": "石油石化",
        "l2_class": "炼化及贸易",
        "l3_class": "",
    },
    {
        "class_code": "750301",
        "l1_class": "石油石化",
        "l2_class": "炼化及贸易",
        "l3_class": "炼油化工",
    },
    {
        "class_code": "750302",
        "l1_class": "石油石化",
        "l2_class": "炼化及贸易",
        "l3_class": "油品石化贸易",
    },
    {
        "class_code": "750303",
        "l1_class": "石油石化",
        "l2_class": "炼化及贸易",
        "l3_class": "其他石化",
    },
    {"class_code": "760000", "l1_class": "环保", "l2_class": "", "l3_class": ""},
    {
        "class_code": "760100",
        "l1_class": "环保",
        "l2_class": "环境治理",
        "l3_class": "",
    },
    {
        "class_code": "760101",
        "l1_class": "环保",
        "l2_class": "环境治理",
        "l3_class": "大气治理",
    },
    {
        "class_code": "760102",
        "l1_class": "环保",
        "l2_class": "环境治理",
        "l3_class": "水务及水治理",
    },
    {
        "class_code": "760103",
        "l1_class": "环保",
        "l2_class": "环境治理",
        "l3_class": "固废治理",
    },
    {
        "class_code": "760104",
        "l1_class": "环保",
        "l2_class": "环境治理",
        "l3_class": "综合环境治理",
    },
    {
        "class_code": "760200",
        "l1_class": "环保",
        "l2_class": "环保设备Ⅱ",
        "l3_class": "",
    },
    {
        "class_code": "760201",
        "l1_class": "环保",
        "l2_class": "环保设备Ⅱ",
        "l3_class": "环保设备Ⅲ",
    },
    {
        "class_code": "770000",
        "l1_class": "美容护理",
        "l2_class": "",
        "l3_class": "",
    },
    {
        "class_code": "770100",
        "l1_class": "美容护理",
        "l2_class": "个护用品",
        "l3_class": "",
    },
    {
        "class_code": "770101",
        "l1_class": "美容护理",
        "l2_class": "个护用品",
        "l3_class": "生活用纸",
    },
    {
        "class_code": "770102",
        "l1_class": "美容护理",
        "l2_class": "个护用品",
        "l3_class": "洗护用品",
    },
    {
        "class_code": "770200",
        "l1_class": "美容护理",
        "l2_class": "化妆品",
        "l3_class": "",
    },
    {
        "class_code": "770201",
        "l1_class": "美容护理",
        "l2_class": "化妆品",
        "l3_class": "化妆品制造及其他",
    },
    {
        "class_code": "770202",
        "l1_class": "美容护理",
        "l2_class": "化妆品",
        "l3_class": "品牌化妆品",
    },
    {
        "class_code": "770300",
        "l1_class": "美容护理",
        "l2_class": "医疗美容",
        "l3_class": "",
    },
    {
        "class_code": "770301",
        "l1_class": "美容护理",
        "l2_class": "医疗美容",
        "l3_class": "医美耗材",
    },
    {
        "class_code": "770302",
        "l1_class": "美容护理",
        "l2_class": "医疗美容",
        "l3_class": "医美服务",
    },
]
